# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
dist: trusty
language: R
sudo: false
cache: packages

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
